language: python

sudo: true

branches:
  only:
    - master

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get update
  - sudo apt-get install -y libfreetype6-dev libfontconfig1-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - . "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes --quiet conda
  - conda install -n root conda conda-env anaconda-client
  - conda info -a
  - conda create -n nb_conda python=$TRAVIS_PYTHON_VERSION
  - conda install -n nb_conda -c conda-forge --file requirements.txt
  - conda activate nb_conda
  - pip install python-coveralls
  - npm install

script:
  - pip install -e .
  - jupyter nbextension install nb_conda --py --sys-prefix --symlink
  - jupyter nbextension enable nb_conda --py --sys-prefix
  - jupyter serverextension enable nb_conda --py --sys-prefix
  - npm run test

after_success:
  - coveralls
